export const nodeData = [
  {
    id: 'Pablo Picasso',
    type: 'Artist',
    color: '#534400',
    group: 1,
    zh: '巴勃羅畢加索',
    es: 'Pablo Picasso',
    it: 'Pablo Picasso',
    fr: 'Pablo Picasso',
    de: 'Pablo Picasso',
    en: 'Pablo Picasso',
  },
  {
    id: 'Johann Sebastian Bach',
    type: 'Artist',
    color: '#534400',
    group: 1,
    zh: '約翰·塞巴斯蒂安·巴赫',
    es: 'Johann Sebastian Bach',
    it: 'Johann Sebastian Bach',
    fr: 'Jean-Sébastien Bach',
    de: 'Johann Sebastian Bach',
    en: 'Johann Sebastian Bach',
  },
  {
    id: 'CHSA',
    type: 'Organization',
    color: 'red',
    group: 1,
    zh: '美國中國歷史學會',
    es: 'Sociedad Histórica China de América',
    it: "Società storica cinese d'America",
    fr: "Société historique chinoise d'Amérique",
    de: 'Chinesische Historische Gesellschaft von Amerika',
    en: 'Chinese Historical Society of America',
  },
  {
    id: 'Richard Strauss',
    type: 'Artist',
    color: '#534400',
    group: 1,
    zh: '理查·施特勞斯',
    es: 'Richard Strauss',
    it: 'Riccardo Strauss',
    fr: 'Richard Strauss',
    de: 'Richard Strauß',
    en: 'Richard Strauss',
  },
  {
    id: 'Gucci Mane',
    type: 'Artist',
    color: '#534400',
    group: 1,
    zh: '古馳鬃毛',
    es: 'Gucci Mane',
    it: 'Gucci Mane',
    fr: 'Gucci Mane',
    de: 'Gucci Mähne',
    en: 'Gucci Mane',
  },
  {
    id: 'William Durant',
    type: 'Business',
    color: '#534400',
    group: 1,
    zh: '威廉杜蘭特',
    es: 'William Durant',
    it: 'William Durant',
    fr: 'Guillaume Durant',
    de: 'William Durant',
    en: 'William Durant',
  },
  {
    id: 'Henry Ford',
    type: 'Business',
    color: '#534400',
    group: 1,
    zh: '亨利·福特',
    es: 'Henry Ford',
    it: 'Henry Ford',
    fr: 'Henry Ford',
    de: 'Henry Ford',
    en: 'Henry Ford',
  },
  {
    id: 'William Clement Stone',
    type: 'Business',
    color: '#534400',
    group: 1,
    zh: '威廉克萊門特斯通',
    es: 'William Clement Stone',
    it: 'William Clemente Pietra',
    fr: 'Pierre William Clément',
    de: 'William Clemens Stone',
    en: 'William Clement Stone',
  },
  {
    id: 'Andrew Carnegie',
    type: 'Business',
    color: '#534400',
    group: 1,
    zh: '安德魯·卡內基',
    es: 'Andrew Carnegie',
    it: 'Andrea Carnegie',
    fr: 'Andrew Carnegie',
    de: 'Andrew Carnegie',
    en: 'Andrew Carnegie',
  },
  {
    id: 'Jiddu Krishnamurti',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '吉都克里希那穆提',
    es: 'Jiddu Krishnamurti',
    it: 'Jiddu Krishnamurti',
    fr: 'Jiddu Krishnamurti',
    de: 'Jiddu Krishnamurti',
    en: 'Jiddu Krishnamurti',
  },
  {
    id: 'Arthur Schopenhauer',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '阿瑟·叔本華',
    es: 'Arthur Schopenhauer',
    it: 'Arthur Schopenhauer',
    fr: 'Arthur Schopenhauer',
    de: 'Arthur Schopenhauer',
    en: 'Arthur Schopenhauer',
  },
  {
    id: 'Bertrand Russell',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '伯特蘭·羅素',
    es: 'Bertrand Russell',
    it: 'Bertrand Russel',
    fr: 'Bertrand Russell',
    de: 'Bertrand Russell',
    en: 'Bertrand Russell',
  },
  {
    id: 'Michael Foucult',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '邁克爾·福柯',
    es: 'Michael Foucult',
    it: 'Michele Foucult',
    fr: 'Michel Foucult',
    de: 'Michael Foucult',
    en: 'Michael Foucult',
  },
  {
    id: 'Immanuel Kant',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '伊曼紐爾康德',
    es: 'Immanuel Kant',
    it: 'Emanuele Kant',
    fr: 'Emmanuel Kant',
    de: 'Immanuel Kant',
    en: 'Immanuel Kant',
  },
  {
    id: 'Thomas Paine',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '托馬斯·潘恩',
    es: 'Thomas Paine',
    it: 'Tommaso Paine',
    fr: 'Thomas Paine',
    de: 'Thomas Paine',
    en: 'Thomas Paine',
  },
  {
    id: 'Baron de Montesquieu',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '孟德斯鳩男爵',
    es: 'Baron de Montesquieu',
    it: 'Barone de Montesquieu',
    fr: 'Baron de Montesquieu',
    de: 'Baron von Montesquieu',
    en: 'Baron de Montesquieu',
  },
  {
    id: 'George Berkeley',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '喬治伯克利',
    es: 'George Berkeley',
    it: 'Giorgio Berkeley',
    fr: 'Georges Berkeley',
    de: 'George Berkeley',
    en: 'George Berkeley',
  },
  {
    id: 'David Hume',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '大衛休謨',
    es: 'David Hume',
    it: 'David Hume',
    fr: 'David Hume',
    de: 'David Hume',
    en: 'David Hume',
  },
  {
    id: 'Adam Smith',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '亞當·斯密',
    es: 'Adam Smith',
    it: 'Adam Smith',
    fr: 'Adam Smith',
    de: 'Adam Smith',
    en: 'Adam Smith',
  },
  {
    id: 'Thomas Reid',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '托馬斯·里德',
    es: 'Thomas Reid',
    it: 'Tommaso Reid',
    fr: 'Thomas Reid',
    de: 'Thomas Reid',
    en: 'Thomas Reid',
  },
  {
    id: 'John Locke',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '約翰洛克',
    es: 'John Locke',
    it: 'John Locke',
    fr: 'John Locke',
    de: 'John Locke',
    en: 'John Locke',
  },
  {
    id: 'Voltaire',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '伏爾泰',
    es: 'Voltaire',
    it: 'Voltaire',
    fr: 'Voltaire',
    de: 'Voltaire',
    en: 'Voltaire',
  },
  {
    id: 'Jean-Jacques Rousseau',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '讓-雅克·盧梭',
    es: 'Jean-Jacques Rousseau',
    it: 'Jean-Jacques Rousseau',
    fr: 'Jean-Jacques Rousseau',
    de: 'Jean-Jacques Rousseau',
    en: 'Jean-Jacques Rousseau',
  },
  {
    id: 'Rene Descartes',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '笛卡爾',
    es: 'Rene Descartes',
    it: 'Renè Cartesio',
    fr: 'René Descartes',
    de: 'René Descartes',
    en: 'Rene Descartes',
  },
  {
    id: 'Baruch Spinoza',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '巴魯克·斯賓諾莎',
    es: 'Baruch Spinoza',
    it: 'Baruch Spinoza',
    fr: 'Baruch Spinoza',
    de: 'Baruch Spinoza',
    en: 'Baruch Spinoza',
  },
  {
    id: 'Auguste Comte',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '奧古斯特孔德',
    es: 'Auguste Comte',
    it: 'Augusto Conte',
    fr: 'Auguste Comté',
    de: 'August Comte',
    en: 'Auguste Comte',
  },
  {
    id: 'Karl Marx',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '卡爾·馬克思',
    es: 'Karl Marx',
    it: 'Carlo Marx',
    fr: 'Karl Marx',
    de: 'Karl Marx',
    en: 'Karl Marx',
  },
  {
    id: 'Sextus Empiricus',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '經驗主義',
    es: 'Sextus Empiricus',
    it: 'Sesto Empirico',
    fr: 'Sextus Empiricus',
    de: 'Sextus Empiricus',
    en: 'Sextus Empiricus',
  },
  {
    id: 'Aristotle',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '亞里士多德',
    es: 'Aristotle',
    it: 'Aristotele',
    fr: 'Aristote',
    de: 'Aristoteles',
    en: 'Aristotle',
  },
  {
    id: 'Plato',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '柏拉圖',
    es: 'Plato',
    it: 'Platone',
    fr: 'Platon',
    de: 'Plato',
    en: 'Plato',
  },
  {
    id: 'Socrates',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '蘇格拉底',
    es: 'Socrates',
    it: 'Socrate',
    fr: 'Socrate',
    de: 'Sokrates',
    en: 'Socrates',
  },
  {
    id: 'Chuang Tzu',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '莊子',
    es: 'Chuang Tzu',
    it: 'Chuang Tzu',
    fr: 'Chuang Tzu',
    de: 'Chuang Tzu',
    en: 'Chuang Tzu',
  },
  {
    id: 'Mencius',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '孟子',
    es: 'Mencius',
    it: 'Mencio',
    fr: 'Mencius',
    de: 'Menzius',
    en: 'Mencius',
  },
  {
    id: 'Confucious',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '孔子',
    es: 'Confucious',
    it: 'Confucio',
    fr: 'Confucius',
    de: 'Konfuzius',
    en: 'Confucious',
  },
  {
    id: 'Laozi',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '老子',
    es: 'Laozi',
    it: 'Laozi',
    fr: 'Laozi',
    de: 'Laozi',
    en: 'Laozi',
  },
  {
    id: 'Friedrich Wilhelm Nietzsche',
    type: 'Philosopher',
    color: '#534400',
    group: 1,
    zh: '弗里德里希·威廉·尼采',
    es: 'Friedrich Wilhelm Nietzsche',
    it: 'Federico Guglielmo Nietzsche',
    fr: 'Frédéric Wilhelm Nietzsche',
    de: 'Friedrich Wilhelm Nietzsche',
    en: 'Friedrich Wilhelm Nietzsche',
  },
  {
    id: 'Carl Jung',
    type: 'Psychologist',
    color: '#534400',
    group: 1,
    zh: '卡爾·榮格',
    es: 'Carl Jung',
    it: 'Carlo Jung',
    fr: 'Carl Jung',
    de: 'Karl Jung',
    en: 'Carl Jung',
  },
  {
    id: 'Sigmund Freud',
    type: 'Psychologist',
    color: '#534400',
    group: 1,
    zh: '西格蒙德·弗洛伊德',
    es: 'Sigmund Freud',
    it: 'Sigmund Freud',
    fr: 'Sigmund Freud',
    de: 'Sigmund Freud',
    en: 'Sigmund Freud',
  },
  {
    id: 'Carl Rogers',
    type: 'Psychologist',
    color: '#534400',
    group: 1,
    zh: '卡爾·羅傑斯',
    es: 'Carl Rogers',
    it: 'Carlo Rogers',
    fr: 'Carl Rogers',
    de: 'Carl Rogers',
    en: 'Carl Rogers',
  },
  {
    id: 'Nicolas Malebranche',
    type: 'Religion',
    color: '#534400',
    group: 1,
    zh: '尼古拉斯·馬勒布蘭奇',
    es: 'Nicolas Malebranche',
    it: 'Nicolas Malebranche',
    fr: 'Nicolas Malebranche',
    de: 'Nikolaus Malebranche',
    en: 'Nicolas Malebranche',
  },
  {
    id: 'Thomas Aquinas',
    type: 'Religion',
    color: '#534400',
    group: 1,
    zh: '托馬斯·阿奎那',
    es: 'Thomas Aquinas',
    it: "Tommaso d'Aquino",
    fr: "Thomas d'Aquin",
    de: 'Thomas von Aquin',
    en: 'Thomas Aquinas',
  },
  {
    id: 'Dalai Lama',
    type: 'Religion',
    color: '#534400',
    group: 1,
    zh: '達賴喇嘛',
    es: 'Dalai Lama',
    it: 'Dalai Lama',
    fr: 'Dalaï Lama',
    de: 'Dalai Lama',
    en: 'Dalai Lama',
  },
  {
    id: 'Thomas Merton',
    type: 'Religion',
    color: '#534400',
    group: 1,
    zh: '托馬斯·默頓',
    es: 'Thomas Merton',
    it: 'Tommaso Merton',
    fr: 'Thomas Merton',
    de: 'Thomas Merton',
    en: 'Thomas Merton',
  },
  {
    id: 'Albert Einstein',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '艾爾伯特愛因斯坦',
    es: 'Albert Einstein',
    it: 'Albert Einstein',
    fr: 'Albert Einstein',
    de: 'Albert Einstein',
    en: 'Albert Einstein',
  },
  {
    id: 'Charles Darwin',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '查爾斯·達爾文',
    es: 'Charles Darwin',
    it: 'Carlo Darwin',
    fr: 'Charles Darwin',
    de: 'Charles Darwin',
    en: 'Charles Darwin',
  },
  {
    id: 'Issac Newton',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '艾薩克·牛頓',
    es: 'Issac Newton',
    it: 'Isacco Newton',
    fr: 'Isaac Newton',
    de: 'Issac Newton',
    en: 'Issac Newton',
  },
  {
    id: 'Galileo Galilei',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '伽利略·伽利雷',
    es: 'Galileo Galilei',
    it: 'Galileo Galilei',
    fr: 'Galilée',
    de: 'Galileo Galilei',
    en: 'Galileo Galilei',
  },
  {
    id: 'Nicolaus Copernicus',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '尼古拉·哥白尼',
    es: 'Nicolaus Copernicus',
    it: 'Niccolò Copernico',
    fr: 'Nicolaus Copernicus',
    de: 'Nikolaus Kopernikus',
    en: 'Nicolaus Copernicus',
  },
  {
    id: 'Ibn Sina',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '伊本·西納',
    es: 'Ibn Sina',
    it: 'Ibn Sina',
    fr: 'Ibn Sina',
    de: 'Ibn Sina',
    en: 'Ibn Sina',
  },
  {
    id: 'Ibn Tufail',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '伊本·圖費爾',
    es: 'Ibn Tufail',
    it: 'Ibn Tufail',
    fr: 'Ibn Tufaïl',
    de: 'Ibn Tufail',
    en: 'Ibn Tufail',
  },
  {
    id: 'Thomas Edison',
    type: 'Scientist',
    color: '#534400',
    group: 1,
    zh: '托馬斯·愛迪生',
    es: 'Thomas Edison',
    it: 'Tommaso Edison',
    fr: 'Thomas Edison',
    de: 'Thomas Edison',
    en: 'Thomas Edison',
  },
  {
    id: 'Benjamin Franklin',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '本傑明·富蘭克林',
    es: 'Benjamin Franklin',
    it: 'Benjamin Franklin',
    fr: 'Benjamin Franklin',
    de: 'Benjamin Franklin',
    en: 'Benjamin Franklin',
  },
  {
    id: 'Theodore Roosevelt',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '西奧多·羅斯福',
    es: 'Theodore Roosevelt',
    it: 'Theodore Roosevelt',
    fr: 'Théodore Roosevelt',
    de: 'Theodore Roosevelt',
    en: 'Theodore Roosevelt',
  },
  {
    id: 'John F. Kennedy',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '約翰·肯尼迪',
    es: 'John F. Kennedy',
    it: 'John F. Kennedy',
    fr: 'John F. Kennedy',
    de: 'John F. Kennedy',
    en: 'John F. Kennedy',
  },
  {
    id: 'Sun Yat Sen',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '孫中山',
    es: 'Sun Yat Sen',
    it: 'Sun Yat Sen',
    fr: 'Sun Yat Sen',
    de: 'Sun Yat-sen',
    en: 'Sun Yat Sen',
  },
  {
    id: 'Qin Shi Huang',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '秦始皇',
    es: 'Qin Shi Huang',
    it: 'Qin Shi Huang',
    fr: 'Qin Shi Huang',
    de: 'Qin Shi Huang',
    en: 'Qin Shi Huang',
  },
  {
    id: 'Takeda Shingen',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '武田信玄',
    es: 'Takeda Shingen',
    it: 'Takeda Shingen',
    fr: 'Takeda Shingen',
    de: 'Takeda Shingen',
    en: 'Takeda Shingen',
  },
  {
    id: 'Sun Tzu',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '孫子',
    es: 'Sun Tzu',
    it: 'Sun Tzu',
    fr: 'Sun Tzu',
    de: 'Sonne Tzu',
    en: 'Sun Tzu',
  },
  {
    id: 'Ho Chi Minh',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '胡志明',
    es: 'Ho Chi Minh',
    it: 'Ho Chi Minh',
    fr: 'Ho Chi Minh',
    de: 'Ho Chi Minh',
    en: 'Ho Chi Minh',
  },
  {
    id: 'Abraham Lincoln',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '亞伯拉罕·林肯',
    es: 'Abraham Lincoln',
    it: 'Abraham Lincoln',
    fr: 'Abraham Lincoln',
    de: 'Abraham Lincoln',
    en: 'Abraham Lincoln',
  },
  {
    id: 'Donald Trump',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '唐納德·特朗普',
    es: 'Donald Trump',
    it: 'Donald Trump',
    fr: 'Donald Trump',
    de: 'Donald Trump',
    en: 'Donald Trump',
  },
  {
    id: 'Richard Nixon',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '理查德尼克松',
    es: 'Richard Nixon',
    it: 'Richard Nixon',
    fr: 'Richard Nixon',
    de: 'Richard Nixon',
    en: 'Richard Nixon',
  },
  {
    id: 'Mao Ze Dong',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '毛澤東',
    es: 'Mao Ze Dong',
    it: 'Mao Ze Dong',
    fr: 'Mao Zedong',
    de: 'Mao Ze Dong',
    en: 'Mao Ze Dong',
  },
  {
    id: 'Gerald Ford',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '杰拉爾德福特',
    es: 'Gerald Ford',
    it: 'Gerald Ford',
    fr: 'Gérald Ford',
    de: 'Gerhard Ford',
    en: 'Gerald Ford',
  },
  {
    id: 'Jimmy Carter',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '吉米卡特',
    es: 'Jimmy Carter',
    it: 'Jimmy Carter',
    fr: 'Jimmy Carter',
    de: 'Jimmy Carter',
    en: 'Jimmy Carter',
  },
  {
    id: 'Ronald Reagan',
    type: 'Statesman',
    color: '#534400',
    group: 1,
    zh: '羅納德·裡根',
    es: 'Ronald Reagan',
    it: 'Ronald Reagan',
    fr: 'Ronald Reagan',
    de: 'Ronald Reagan',
    en: 'Ronald Reagan',
  },
  {
    id: 'Miyamoto Musashi',
    type: 'Warrior',
    color: '#534400',
    group: 1,
    zh: '宮本武藏',
    es: 'Miyamoto Musashi',
    it: 'Miyamoto Musashi',
    fr: 'Miyamoto Musashi',
    de: 'Miyamoto Musashi',
    en: 'Miyamoto Musashi',
  },
  {
    id: 'Alan Watts',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '艾倫·瓦茨',
    es: 'Alan Watts',
    it: 'Alan Watt',
    fr: 'Alan Watts',
    de: 'Alan Watt',
    en: 'Alan Watts',
  },
  {
    id: 'Joseph Campbell',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '約瑟夫·坎貝爾',
    es: 'Joseph Campbell',
    it: 'Giuseppe Campbell',
    fr: 'Joseph Campbell',
    de: 'Josef Campell',
    en: 'Joseph Campbell',
  },
  {
    id: 'William Shakespeare',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '威廉·莎士比亞',
    es: 'William Shakespeare',
    it: 'William Shakespeare',
    fr: 'William Shakespeare',
    de: 'William Shakespeare',
    en: 'William Shakespeare',
  },
  {
    id: 'George Elliot',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '喬治·艾略特',
    es: 'George Elliot',
    it: 'Giorgio Elliot',
    fr: 'Georges Elliot',
    de: 'Georg Elliot',
    en: 'George Elliot',
  },
  {
    id: 'Johann Wolfgang von Goethe',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '約翰·沃爾夫岡·馮·歌德',
    es: 'Johann Wolfgang von Goethe',
    it: 'Johann Wolfgang von Goethe',
    fr: 'Johann Wolfgang von Goethe',
    de: 'Johann Wolfgang von Goethe',
    en: 'Johann Wolfgang von Goethe',
  },
  {
    id: 'Baltasar Gracian',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '巴爾塔薩·格拉西安',
    es: 'Baltasar Gracian',
    it: 'Baltasar Graziano',
    fr: 'Baltasar Gracian',
    de: 'Baltasar Gracian',
    en: 'Baltasar Gracian',
  },
  {
    id: 'Homer',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '荷馬',
    es: 'Homer',
    it: 'Omero',
    fr: 'Homère',
    de: 'Homer',
    en: 'Homer',
  },
  {
    id: 'Nitobe Inazo',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '新戶部稻三',
    es: 'Nitobe Inazo',
    it: 'Nitobe Inazo',
    fr: 'Nitobé Inazo',
    de: 'Nitobe Inazo',
    en: 'Nitobe Inazo',
  },
  {
    id: 'Herman Hess',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '赫爾曼·赫斯',
    es: 'Herman Hess',
    it: 'Herman Hess',
    fr: 'Hermann Hess',
    de: 'Hermann Heß',
    en: 'Herman Hess',
  },
  {
    id: 'Frank Bettger',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '弗蘭克·貝特格',
    es: 'Frank Bettger',
    it: 'Frank Betger',
    fr: 'Franck Bettger',
    de: 'Frank Better',
    en: 'Frank Bettger',
  },
  {
    id: 'Dale Carnegie',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '戴爾卡耐基',
    es: 'Dale Carnegie',
    it: 'Dale Carnegie',
    fr: 'Dale Carnegie',
    de: 'Dale Carnegie',
    en: 'Dale Carnegie',
  },
  {
    id: 'Norman Vincent Peale',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '諾曼文森特皮爾',
    es: 'Norman Vincent Peale',
    it: 'Norman Vincent Peale',
    fr: 'Norman Vincent Peale',
    de: 'Norman Vincent Peale',
    en: 'Norman Vincent Peale',
  },
  {
    id: 'James Allen (author)',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '詹姆斯·艾倫',
    es: 'James Allen',
    it: 'James Allen',
    fr: 'James Allen',
    de: 'James Allen',
    en: 'James Allen',
  },
  {
    id: 'Napolean Hill',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '拿破崙山',
    es: 'Napolean Hill',
    it: 'Colle Napoleone',
    fr: 'Colline Napoléonienne',
    de: 'Napoleons Hügel',
    en: 'Napolean Hill',
  },
  {
    id: 'Ernest Hemingway',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '海明威',
    es: 'Ernest Hemingway',
    it: 'Ernest Hemingway',
    fr: 'Ernest Hemingway',
    de: 'Ernest Hemingway',
    en: 'Ernest Hemingway',
  },
  {
    id: 'Mark Twain',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '馬克吐溫',
    es: 'Mark Twain',
    it: 'Mark Twin',
    fr: 'Mark Twain',
    de: 'Mark Twain',
    en: 'Mark Twain',
  },
  {
    id: 'Henry James',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '亨利詹姆斯',
    es: 'Henry James',
    it: 'Enrico Giacomo',
    fr: 'Henri James',
    de: 'Heinrich James',
    en: 'Henry James',
  },
  {
    id: 'Stephen Crane',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '斯蒂芬·克蘭',
    es: 'Stephen Crane',
    it: 'Stefano Gru',
    fr: 'Stephen Crane',
    de: 'Stefan Kran',
    en: 'Stephen Crane',
  },
  {
    id: 'Clive Staples Lewis',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '克萊夫·斯台普斯·劉易斯',
    es: 'Clive Staples Lewis',
    it: 'Clive Staples Lewis',
    fr: 'Clive StaplesLewis',
    de: 'Clive Staples Lewis',
    en: 'Clive Staples Lewis',
  },
  {
    id: 'Joanne Rowling',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '喬安妮·羅琳',
    es: 'Joanne Rowling',
    it: 'Giovanna Rowling',
    fr: 'Joanne Rowling',
    de: 'Joanne Rowling',
    en: 'Joanne Rowling',
  },
  {
    id: 'John Ronald Reuel Tolkien',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '約翰·羅納德·魯爾·托爾金',
    es: 'John Ronald Reuel Tolkien',
    it: 'John Ronald Reuel Tolkien',
    fr: 'John Ronald Reuel Tolkien',
    de: 'John Ronald Reuel Tolkien',
    en: 'John Ronald Reuel Tolkien',
  },
  {
    id: 'William Strunk Jr',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '小威廉·斯特倫克',
    es: 'William Strunk Jr',
    it: 'William Strunk Jr',
    fr: 'William Strunk Jr.',
    de: 'William Strunk jr',
    en: 'William Strunk Jr',
  },
  {
    id: 'Dorothy Parker',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '多蘿西·帕克',
    es: 'Dorothy Parker',
    it: 'Dorothy Parker',
    fr: 'Dorothée Parker',
    de: 'Dorothy Parker',
    en: 'Dorothy Parker',
  },
  {
    id: 'Stephen King',
    type: 'Writer',
    color: '#534400',
    group: 1,
    zh: '斯蒂芬·金',
    es: 'Stephen King',
    it: 'Stephen King',
    fr: 'Stephen King',
    de: 'Stephen King',
    en: 'Stephen King',
  },
  {
    id: 'Bruce Lee',
    type: '',
    color: '#FED206',
    group: 1,
    zh: '李小龍',
    es: 'Bruce Lee',
    it: 'Bruce Lee',
    fr: 'Bruce Lee',
    de: 'Bruce Lee',
    en: 'Bruce Lee',
  },
];

export const linkData = [
  {
    source: 'Henry James',
    target: 'Ernest Hemingway',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'CHSA',
    value: 1,
  },
  {
    source: 'Mark Twain',
    target: 'Ernest Hemingway',
    value: 1,
  },
  {
    source: 'Stephen Crane',
    target: 'Ernest Hemingway',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Stephen Crane',
    value: 1,
  },
  {
    source: 'William Strunk Jr',
    target: 'William Shakespeare',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'William Strunk Jr',
    value: 1,
  },
  {
    source: 'Dorothy Parker',
    target: 'William Strunk Jr',
    value: 1,
  },
  {
    source: 'Stephen King',
    target: 'William Strunk Jr',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Socrates',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Plato',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Aristotle',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Friedrich Wilhelm Nietzsche',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'William Durant',
    target: 'Homer',
    value: 1,
  },
  {
    source: 'Clive Staples Lewis',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Clive Staples Lewis',
    target: 'John Ronald Reuel Tolkien',
    value: 1,
  },
  {
    source: 'Joanne Rowling',
    target: 'Clive Staples Lewis',
    value: 1,
  },
  {
    source: 'Ronald Reagan',
    target: 'Clive Staples Lewis',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Thomas Merton',
    value: 1,
  },
  {
    source: 'Thomas Merton',
    target: 'Dalai Lama',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Miyamoto Musashi',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Jiddu Krishnamurti',
    value: 1,
  },
  {
    source: 'Jiddu Krishnamurti',
    target: 'Theodore Roosevelt',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Chuang Tzu',
    value: 1,
  },
  {
    source: 'Laozi',
    target: 'Chuang Tzu',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Herman Hess',
    value: 1,
  },
  {
    source: 'Herman Hess',
    target: 'Richard Strauss',
    value: 1,
  },
  {
    source: 'Qin Shi Huang',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Takeda Shingen',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Ho Chi Minh',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Miyamoto Musashi',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Mao Ze Dong',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Laozi',
    target: 'Sun Tzu',
    value: 1,
  },
  {
    source: 'Confucious',
    target: 'Mao Ze Dong',
    value: 1,
  },
  {
    source: 'Sun Yat Sen',
    target: 'Confucious',
    value: 1,
  },
  {
    source: 'Confucious',
    target: 'Voltaire',
    value: 1,
  },
  {
    source: 'Confucious',
    target: 'Mencius',
    value: 1,
  },
  {
    source: 'Nitobe Inazo',
    target: 'Mencius',
    value: 1,
  },
  {
    source: 'Nitobe Inazo',
    target: 'Theodore Roosevelt',
    value: 1,
  },
  {
    source: 'Nitobe Inazo',
    target: 'John F. Kennedy',
    value: 1,
  },
  {
    source: 'Frank Bettger',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Frank Bettger',
    target: 'Benjamin Franklin',
    value: 1,
  },
  {
    source: 'Frank Bettger',
    target: 'Henry Ford',
    value: 1,
  },
  {
    source: 'Frank Bettger',
    target: 'Abraham Lincoln',
    value: 1,
  },
  {
    source: 'Dale Carnegie',
    target: 'Frank Bettger',
    value: 1,
  },
  {
    source: 'Dale Carnegie',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'William Clement Stone',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'William Clement Stone',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'Thomas Edison',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'Henry Ford',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'Sun Tzu',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'Andrew Carnegie',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'Theodore Roosevelt',
    target: 'Napolean Hill',
    value: 1,
  },
  {
    source: 'James Allen (author)',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'James Allen (author)',
    target: 'Gucci Mane',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Ronald Reagan',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Jimmy Carter',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Gerald Ford',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Richard Nixon',
    value: 1,
  },
  {
    source: 'Norman Vincent Peale',
    target: 'Donald Trump',
    value: 1,
  },
  {
    source: 'Jiddu Krishnamurti',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Jiddu Krishnamurti',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Alan Watts',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Alan Watts',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Plato',
    value: 1,
  },
  {
    source: 'Carl Rogers',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Carl Rogers',
    target: 'Carl Jung',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Carl Jung',
    value: 1,
  },
  {
    source: 'Alan Watts',
    target: 'Carl Jung',
    value: 1,
  },
  {
    source: 'Carl Jung',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'Thomas Aquinas',
    value: 1,
  },
  {
    source: 'George Berkeley',
    target: 'Rene Descartes',
    value: 1,
  },
  {
    source: 'George Berkeley',
    target: 'Ibn Tufail',
    value: 1,
  },
  {
    source: 'George Berkeley',
    target: 'Issac Newton',
    value: 1,
  },
  {
    source: 'George Berkeley',
    target: 'John Locke',
    value: 1,
  },
  {
    source: 'Friedrich Wilhelm Nietzsche',
    target: 'Carl Jung',
    value: 1,
  },
  {
    source: 'Friedrich Wilhelm Nietzsche',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Friedrich Wilhelm Nietzsche',
    target: 'Michael Foucult',
    value: 1,
  },
  {
    source: 'Pablo Picasso',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'Joseph Campbell',
    value: 1,
  },
  {
    source: 'Carl Jung',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Bruce Lee',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Friedrich Wilhelm Nietzsche',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Bertrand Russell',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Thomas Paine',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Issac Newton',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Immanuel Kant',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Charles Darwin',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Auguste Comte',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Adam Smith',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Thomas Reid',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'John Locke',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Thomas Paine',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Bertrand Russell',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Bertrand Russell',
    target: 'John Locke',
    value: 1,
  },
  {
    source: 'Benjamin Franklin',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Jean-Jacques Rousseau',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Voltaire',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Voltaire',
    target: 'Issac Newton',
    value: 1,
  },
  {
    source: 'Voltaire',
    target: 'John Locke',
    value: 1,
  },
  {
    source: 'John Locke',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Baruch Spinoza',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Jean-Jacques Rousseau',
    target: 'John Locke',
    value: 1,
  },
  {
    source: 'Voltaire',
    target: 'Jean-Jacques Rousseau',
    value: 1,
  },
  {
    source: 'Nicolas Malebranche',
    target: 'Jean-Jacques Rousseau',
    value: 1,
  },
  {
    source: 'Baron de Montesquieu',
    target: 'Nicolas Malebranche',
    value: 1,
  },
  {
    source: 'Baron de Montesquieu',
    target: 'Thomas Paine',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Nicolas Malebranche',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Voltaire',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'John Locke',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'Rene Descartes',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Immanuel Kant',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Galileo Galilei',
    value: 1,
  },
  {
    source: 'Rene Descartes',
    target: 'Sextus Empiricus',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Sextus Empiricus',
    target: 'David Hume',
    value: 1,
  },
  {
    source: 'Arthur Schopenhauer',
    target: 'Johann Wolfgang von Goethe',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'William Shakespeare',
    value: 1,
  },

  {
    source: 'Johann Sebastian Bach',
    target: 'Johann Wolfgang von Goethe',
    value: 1,
  },

  {
    source: 'Johann Wolfgang von Goethe',
    target: 'Sigmund Freud',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'Immanuel Kant',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'George Elliot',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Baruch Spinoza',
    target: 'Johann Wolfgang von Goethe',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'Jean-Jacques Rousseau',
    value: 1,
  },
  {
    source: 'Baruch Spinoza',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Baruch Spinoza',
    target: 'Albert Einstein',
    value: 1,
  },
  {
    source: 'Karl Marx',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Karl Marx',
    target: 'Mao Ze Dong',
    value: 1,
  },
  {
    source: 'Aristotle',
    target: 'Thomas Aquinas',
    value: 1,
  },
  {
    source: 'Aristotle',
    target: 'Plato',
    value: 1,
  },
  {
    source: 'Aristotle',
    target: 'Socrates',
    value: 1,
  },
  {
    source: 'Plato',
    target: 'Socrates',
    value: 1,
  },
  {
    source: 'Plato',
    target: 'Ibn Tufail',
    value: 1,
  },
  {
    source: 'Plato',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Ibn Tufail',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Aristotle',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Plato',
    target: 'George Elliot',
    value: 1,
  },
  {
    source: 'Ibn Sina',
    target: 'Baruch Spinoza',
    value: 1,
  },
  {
    source: 'Ibn Sina',
    target: 'Nicolaus Copernicus',
    value: 1,
  },
  {
    source: 'Baruch Spinoza',
    target: 'Johann Wolfgang von Goethe',
    value: 1,
  },
  {
    source: 'Galileo Galilei',
    target: 'Nicolaus Copernicus',
    value: 1,
  },
  {
    source: 'Aristotle',
    target: 'Galileo Galilei',
    value: 1,
  },
  {
    source: 'Baltasar Gracian',
    target: 'Bruce Lee',
    value: 1,
  },
  {
    source: 'Baltasar Gracian',
    target: 'Homer',
    value: 1,
  },
  {
    source: 'Johann Wolfgang von Goethe',
    target: 'Homer',
    value: 1,
  },
  {
    source: 'Baltasar Gracian',
    target: 'Plato',
    value: 1,
  },
];
const graphData = {
  nodes: nodeData,
  links: linkData,
};
